# Generated by Django 3.2.4 on 2021-06-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
